# Generated by Django 5.0.2 on 2024-02-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_app", "0004_alter_room_capacity_alter_room_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="projector",
            field=models.BooleanField(default=True),
        ),
    ]
